server:
  port: 8080
  ssl:
    enabled: true
    key-store: "file:/C:/Program Files/Amazon Corretto/jdk11.0.15_9/lib/security/cacerts"
    key-store-password: "changeit"
    key-store-type: "jks"
    key-alias: "okta"
#  ssl:
#    enabled: true
#    key-store-type: PKCS12
#    key-store: classpath:config/localhost.p12
#    key-store-password: changeit
#    trust-store: classpath:config/truststore.jks
#    trust-store-password: changeit
#    trust-store: C:\Program Files\Amazon Corretto\jdk11.0.15_9\lib\security/cacerts
#    trust-store-password: changeit
#    javax:
#      net:
#        ssl:
#          enabled: true
#          trust-store:

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
      
management:
  tracing:
    sampling:
      probability: 1.0      